services:
  # backend service
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file: ./backend/.env
   

  # Frontend service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "3000:3000"
    