services:
  # backend service
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: vikrampatel/syncscript_backend
    ports:
      - "8000:8080"
    env_file: ./backend/.env
   

  # Frontend service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vikrampatel/syncscript_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    